<?php
/**
 * Created by PhpStorm.
 * User: lyon
 * Date: 17-3-10
 * Time: 下午10:09
 */

namespace app\admin\controller;

use app\admin\model\Course as CourseModel;
use think\Controller;
use think\Request;

class Course extends Controller
{
    protected $course;

    public function __construct(Request $request, CourseModel $course)
    {
        parent::__construct($request);
        $this->course = $course;
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('courseActive', 'open'); // 打开菜单
    }

    public function courseList()
    {
        $page = $this->course->pageSelect();

//        var_dump($page);exit;
        $this->assign('courseInfo', $page['list']);
        $this->assign('coursePage', $page['page']);
        $this->assign('courseList', 'active');

        return $this->fetch();
    }

    public function addCourse()
    {
        if (Request::instance()->isPost()) {
            $data = $this->_param();
//            var_dump($data); exit;
            if ($this->course->tableAdd($data)) {
                $this->success('添加成功', '/admin/course/addCourse');
            } else {
                $this->error('添加失败', '/admin/course/addCourse');
            }
        } else {
            $this->assign('addCourse', 'active');
            return $this->fetch();
        }
    }

    /*
     * 提交参数处理
     */

    private function _param()
    {
        $response = Request::instance()->post();
        $data['cname'] = trim($response['courseName']);
        $data['btime'] = $response['beginTime'];
        $data['etime'] = $response['endTime'];
        $data['intro'] = $response['courseIntroduction'];
        $data['raw'] = $response['creditRaw'] * 100;

        return $data;
    }
}