<?php
/**
 * Created by PhpStorm.
 * User: lyon
 * Date: 17-3-12
 * Time: 上午9:10
 */

namespace app\admin\controller;

use app\admin\model\Referrer as ReferrerModel;
use think\Controller;
use think\Request;

class Referrer extends Controller
{
    protected $referrerModel;

    public function __construct(Request $request, ReferrerModel $referrer)
    {
        parent::__construct($request);
        $this->referrerModel = $referrer;
    }

    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('referrerActive', 'open');
    }

    /*
     * 推荐人列表
     */
    public function referrerList()
    {
        $this->assign('referrerList', 'active');

        $page = $this->referrerModel->tableSelect();
        $this->assign('referrerInfo', $page['list']);
        $this->assign('referrerPage', $page['page']);

        return $this->fetch();
    }

    /*
     * 推荐人添加
     */
    public function referrerAdd()
    {
        $this->assign('referrerAdd', 'active');
        if (Request::instance()->isPost()) {
            $data = $this->_param();
            if ($this->referrerModel->tableAdd($data)) {
                $this->success('添加成功', '/admin/referrer/referrerAdd');
            } else {
                $this->error('添加失败', '/admin/referrer/referrerAdd');
            }
        } else {
            return $this->fetch();
        }
    }

    /**
     * 处理提交数据
     */
    private function _param()
    {
        $response = Request::instance()->post();
        $data['nickname'] = trim($response['referrerNickname']);
        $data['name'] = trim($response['referrerName']);
        $data['email'] = trim($response['referrerEmail']);
        $data['gender'] = $response['referrerGender'] == 0 ? '男' : '女';
        $data['company'] = $response['referrerCompany'];
        $data['phone'] = $response['referrerPhone'];
        $data['qq'] = $response['referrerQq'];
        $data['wechat'] = $response['referrerWechat'];
        $data['alibaba'] = $response['referrerAlibaba'];
        $data['password'] = empty($response['referrerPassword']) ? md5('123456') : md5($response['referrerPassword']);

        return $data;
    }
}